### ISSUE TITLE
Create a Form /  Add a List - View 

### ISSUE THREAD

**Issue by MarioPierides** [MarioPierides/capstone-project#1]
## Value Description / Statement

As a User, I want to create a new meeting in a form. So I can choose all my necessary informations for a new appointment and save them in a meeting  ..

## Description

<img width="310" alt="Bildschirmfoto 2022-05-25 um 09 03 37" src="https://user-images.githubusercontent.com/101989959/170200838-b635d383-4d34-4675-86d0-531b2099807e.png">

## Acceptance Criteria

 - [x] The form and the result are on the same page
 - [x] The meeting should display when you click on the button
 - [x] The result contains the details of the meeting
 - [x] The inputs must be 'required'
 - [x] max-length for input titel must 30 characters or less
 - [x] Places- and Activities- field is a dropdown menu. Places: Elbe, Alster, Stadtpark. Activities: Gassi gehen, Sport, sonstiges.
 - [x] The button must have a hover effect to show it is clickable
 - [x] The button need to be big enough to click it on a mobile screen with the finger
 - [x] The button font must be readable

## Tasks

- [x] Create a branch
- [x] Create and push first commit for upstream
- [x] Create a form with three inputs ( 1 Text, 2 Dropdown Menu )
- [x] Create one button under the form to add the appointment as a meeting
- [x] Meeting - view the details of the meeting, when the form is saved

## Complexity

middle

**Comment by F-Kirchhoff** [comment]
Hey Mario, very good! 🦊  I have only a few remarks:
- in the value description, the word 'click' seems a bit out of place, do you mean 'choose' ?
- Please use The form instead of my form in the acceptence criteria
- what do you mean by 'a review of the meeting details' ? I guess you could also say 'contains the details of the meeting'
- You should specify what the possible values of the dropdown menus are
- You named your Meeting Cards 'List'. This might be a bit confusing, since your Meeting Cards are in a List themselves. So you could rename them and say 'Create a meeting card on the page and append it to the Meeting Card list when the form is submitted.
- You have some typos, please check for them as well

But all in all this is a well structured user story with a nice scope. I like it a lot!

**Comment by MarioPierides** [comment]
Hey Felix, thank you for your positiv feedback, a lot of good ideas and suggestions. 
I'll try to complete this things. Thanks!
