### ISSUE TITLE
Continue with form -  create "AgeGroup" (Checkboxes)

### ISSUE THREAD

**Issue by MarioPierides** [MarioPierides/capstone-project#6]

**Comment by MarioPierides** [comment]
## Value Description / Statement

As a User, I want to choose the "Agegroup"(Altergruppe) of my dog. So i can put more necessary informations into my new appointment and save them in a meeting..

## Description

![Bildschirmfoto 2022-05-30 um 12 26 19](https://user-images.githubusercontent.com/101989959/170973217-f4d75724-c367-45d5-9926-a8547a583810.png)


## Acceptance Criteria

 - [x] The form and the result are on the same page
 - [x] The meeting (Display Checkbox) should display when you click on the "ADD" button
 - [x] The result contains the details of the agegroup (checkboxes)
 - [x] Four checkboxes are displayed.
 Range: "Welpen", "Junghunde", "Erwachsen", "Senior" : to check which agegroup is desired
 - [x] The checkboxes are not 'required' 

## Tasks

- [x] Create a branch
- [x] Create and push first commit for upstream
- [x] add a form field with labels / checkboxes(4)
- [x] Form field is controlled within a state + filter and map function.
- [x] Display checkbox results - view the details of the checkboxes, when the form is added.


## Complexity

middle

**Comment by marcbendixen** [comment]
Hey 👋 
this looks good to me!

Maybe there is one little thing that will be helpful to the user: an information about the range of the "Agegroups". This makes it easier for every user to assign the category.
